---
- hosts: all
  user: centos
  become: yes
  become_method: sudo

  tasks:
  - name: Pulling Repository
    git:
      repo: "{{ petclinic_repo }}"
      version: "{{ petclinic_branch }}"
      dest: /var/www/spring-petclinic/